name: Prediksi Hari Besar Islam

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 1 1 *'  # Setiap 1 Januari
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-prediksi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Jalankan script prediksi
      run: |
        python scripts/prediksi_libur_islam.py

    - name: Commit dan Push hasil
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data/libur_islam.tsv
        git commit -m "Update prediksi libur Islam otomatis" || echo "Tidak ada perubahan"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
